/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: remote-v1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "remote-v1.pb-c.h"
void   prometheus__write_request__init
                     (Prometheus__WriteRequest         *message)
{
  static Prometheus__WriteRequest init_value = PROMETHEUS__WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t prometheus__write_request__get_packed_size
                     (const Prometheus__WriteRequest *message)
{
  assert(message->base.descriptor == &prometheus__write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t prometheus__write_request__pack
                     (const Prometheus__WriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &prometheus__write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t prometheus__write_request__pack_to_buffer
                     (const Prometheus__WriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &prometheus__write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Prometheus__WriteRequest *
       prometheus__write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Prometheus__WriteRequest *)
     protobuf_c_message_unpack (&prometheus__write_request__descriptor,
                                allocator, len, data);
}
void   prometheus__write_request__free_unpacked
                     (Prometheus__WriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &prometheus__write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor prometheus__write_request__field_descriptors[2] =
{
  {
    "timeseries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Prometheus__WriteRequest, n_timeseries),
    offsetof(Prometheus__WriteRequest, timeseries),
    &prometheus__time_series__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Prometheus__WriteRequest, n_metadata),
    offsetof(Prometheus__WriteRequest, metadata),
    &prometheus__metric_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned prometheus__write_request__field_indices_by_name[] = {
  1,   /* field[1] = metadata */
  0,   /* field[0] = timeseries */
};
static const ProtobufCIntRange prometheus__write_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor prometheus__write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "prometheus.WriteRequest",
  "WriteRequest",
  "Prometheus__WriteRequest",
  "prometheus",
  sizeof(Prometheus__WriteRequest),
  2,
  prometheus__write_request__field_descriptors,
  prometheus__write_request__field_indices_by_name,
  2,  prometheus__write_request__number_ranges,
  (ProtobufCMessageInit) prometheus__write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
