/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: remote-v1.proto */

#ifndef PROTOBUF_C_remote_2dv1_2eproto__INCLUDED
#define PROTOBUF_C_remote_2dv1_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "types-v1.pb-c.h"

typedef struct _Prometheus__WriteRequest Prometheus__WriteRequest;


/* --- enums --- */


/* --- messages --- */

struct  _Prometheus__WriteRequest
{
  ProtobufCMessage base;
  size_t n_timeseries;
  Prometheus__TimeSeries **timeseries;
  size_t n_metadata;
  Prometheus__MetricMetadata **metadata;
};
#define PROMETHEUS__WRITE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&prometheus__write_request__descriptor) \
    , 0,NULL, 0,NULL }


/* Prometheus__WriteRequest methods */
void   prometheus__write_request__init
                     (Prometheus__WriteRequest         *message);
size_t prometheus__write_request__get_packed_size
                     (const Prometheus__WriteRequest   *message);
size_t prometheus__write_request__pack
                     (const Prometheus__WriteRequest   *message,
                      uint8_t             *out);
size_t prometheus__write_request__pack_to_buffer
                     (const Prometheus__WriteRequest   *message,
                      ProtobufCBuffer     *buffer);
Prometheus__WriteRequest *
       prometheus__write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   prometheus__write_request__free_unpacked
                     (Prometheus__WriteRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Prometheus__WriteRequest_Closure)
                 (const Prometheus__WriteRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor prometheus__write_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_remote_2dv1_2eproto__INCLUDED */
