/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: types-v1.proto */

#ifndef PROTOBUF_C_types_2dv1_2eproto__INCLUDED
#define PROTOBUF_C_types_2dv1_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Prometheus__Label Prometheus__Label;
typedef struct _Prometheus__Sample Prometheus__Sample;
typedef struct _Prometheus__TimeSeries Prometheus__TimeSeries;
typedef struct _Prometheus__MetricMetadata Prometheus__MetricMetadata;


/* --- enums --- */


/* --- messages --- */

struct  _Prometheus__Label
{
  ProtobufCMessage base;
  char *name;
  char *value;
};
#define PROMETHEUS__LABEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&prometheus__label__descriptor) \
    , NULL, NULL }


struct  _Prometheus__Sample
{
  ProtobufCMessage base;
  protobuf_c_boolean has_value;
  double value;
  protobuf_c_boolean has_timestamp;
  int64_t timestamp;
};
#define PROMETHEUS__SAMPLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&prometheus__sample__descriptor) \
    , 0,0, 0,0 }


struct  _Prometheus__TimeSeries
{
  ProtobufCMessage base;
  size_t n_labels;
  Prometheus__Label **labels;
  size_t n_samples;
  Prometheus__Sample **samples;
};
#define PROMETHEUS__TIME_SERIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&prometheus__time_series__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Prometheus__MetricMetadata
{
  ProtobufCMessage base;
};
#define PROMETHEUS__METRIC_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&prometheus__metric_metadata__descriptor) \
     }


/* Prometheus__Label methods */
void   prometheus__label__init
                     (Prometheus__Label         *message);
size_t prometheus__label__get_packed_size
                     (const Prometheus__Label   *message);
size_t prometheus__label__pack
                     (const Prometheus__Label   *message,
                      uint8_t             *out);
size_t prometheus__label__pack_to_buffer
                     (const Prometheus__Label   *message,
                      ProtobufCBuffer     *buffer);
Prometheus__Label *
       prometheus__label__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   prometheus__label__free_unpacked
                     (Prometheus__Label *message,
                      ProtobufCAllocator *allocator);
/* Prometheus__Sample methods */
void   prometheus__sample__init
                     (Prometheus__Sample         *message);
size_t prometheus__sample__get_packed_size
                     (const Prometheus__Sample   *message);
size_t prometheus__sample__pack
                     (const Prometheus__Sample   *message,
                      uint8_t             *out);
size_t prometheus__sample__pack_to_buffer
                     (const Prometheus__Sample   *message,
                      ProtobufCBuffer     *buffer);
Prometheus__Sample *
       prometheus__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   prometheus__sample__free_unpacked
                     (Prometheus__Sample *message,
                      ProtobufCAllocator *allocator);
/* Prometheus__TimeSeries methods */
void   prometheus__time_series__init
                     (Prometheus__TimeSeries         *message);
size_t prometheus__time_series__get_packed_size
                     (const Prometheus__TimeSeries   *message);
size_t prometheus__time_series__pack
                     (const Prometheus__TimeSeries   *message,
                      uint8_t             *out);
size_t prometheus__time_series__pack_to_buffer
                     (const Prometheus__TimeSeries   *message,
                      ProtobufCBuffer     *buffer);
Prometheus__TimeSeries *
       prometheus__time_series__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   prometheus__time_series__free_unpacked
                     (Prometheus__TimeSeries *message,
                      ProtobufCAllocator *allocator);
/* Prometheus__MetricMetadata methods */
void   prometheus__metric_metadata__init
                     (Prometheus__MetricMetadata         *message);
size_t prometheus__metric_metadata__get_packed_size
                     (const Prometheus__MetricMetadata   *message);
size_t prometheus__metric_metadata__pack
                     (const Prometheus__MetricMetadata   *message,
                      uint8_t             *out);
size_t prometheus__metric_metadata__pack_to_buffer
                     (const Prometheus__MetricMetadata   *message,
                      ProtobufCBuffer     *buffer);
Prometheus__MetricMetadata *
       prometheus__metric_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   prometheus__metric_metadata__free_unpacked
                     (Prometheus__MetricMetadata *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Prometheus__Label_Closure)
                 (const Prometheus__Label *message,
                  void *closure_data);
typedef void (*Prometheus__Sample_Closure)
                 (const Prometheus__Sample *message,
                  void *closure_data);
typedef void (*Prometheus__TimeSeries_Closure)
                 (const Prometheus__TimeSeries *message,
                  void *closure_data);
typedef void (*Prometheus__MetricMetadata_Closure)
                 (const Prometheus__MetricMetadata *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor prometheus__label__descriptor;
extern const ProtobufCMessageDescriptor prometheus__sample__descriptor;
extern const ProtobufCMessageDescriptor prometheus__time_series__descriptor;
extern const ProtobufCMessageDescriptor prometheus__metric_metadata__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_types_2dv1_2eproto__INCLUDED */
