/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: types-v1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "types-v1.pb-c.h"
void   prometheus__label__init
                     (Prometheus__Label         *message)
{
  static Prometheus__Label init_value = PROMETHEUS__LABEL__INIT;
  *message = init_value;
}
size_t prometheus__label__get_packed_size
                     (const Prometheus__Label *message)
{
  assert(message->base.descriptor == &prometheus__label__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t prometheus__label__pack
                     (const Prometheus__Label *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &prometheus__label__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t prometheus__label__pack_to_buffer
                     (const Prometheus__Label *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &prometheus__label__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Prometheus__Label *
       prometheus__label__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Prometheus__Label *)
     protobuf_c_message_unpack (&prometheus__label__descriptor,
                                allocator, len, data);
}
void   prometheus__label__free_unpacked
                     (Prometheus__Label *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &prometheus__label__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   prometheus__sample__init
                     (Prometheus__Sample         *message)
{
  static Prometheus__Sample init_value = PROMETHEUS__SAMPLE__INIT;
  *message = init_value;
}
size_t prometheus__sample__get_packed_size
                     (const Prometheus__Sample *message)
{
  assert(message->base.descriptor == &prometheus__sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t prometheus__sample__pack
                     (const Prometheus__Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &prometheus__sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t prometheus__sample__pack_to_buffer
                     (const Prometheus__Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &prometheus__sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Prometheus__Sample *
       prometheus__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Prometheus__Sample *)
     protobuf_c_message_unpack (&prometheus__sample__descriptor,
                                allocator, len, data);
}
void   prometheus__sample__free_unpacked
                     (Prometheus__Sample *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &prometheus__sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   prometheus__time_series__init
                     (Prometheus__TimeSeries         *message)
{
  static Prometheus__TimeSeries init_value = PROMETHEUS__TIME_SERIES__INIT;
  *message = init_value;
}
size_t prometheus__time_series__get_packed_size
                     (const Prometheus__TimeSeries *message)
{
  assert(message->base.descriptor == &prometheus__time_series__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t prometheus__time_series__pack
                     (const Prometheus__TimeSeries *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &prometheus__time_series__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t prometheus__time_series__pack_to_buffer
                     (const Prometheus__TimeSeries *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &prometheus__time_series__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Prometheus__TimeSeries *
       prometheus__time_series__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Prometheus__TimeSeries *)
     protobuf_c_message_unpack (&prometheus__time_series__descriptor,
                                allocator, len, data);
}
void   prometheus__time_series__free_unpacked
                     (Prometheus__TimeSeries *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &prometheus__time_series__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   prometheus__metric_metadata__init
                     (Prometheus__MetricMetadata         *message)
{
  static Prometheus__MetricMetadata init_value = PROMETHEUS__METRIC_METADATA__INIT;
  *message = init_value;
}
size_t prometheus__metric_metadata__get_packed_size
                     (const Prometheus__MetricMetadata *message)
{
  assert(message->base.descriptor == &prometheus__metric_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t prometheus__metric_metadata__pack
                     (const Prometheus__MetricMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &prometheus__metric_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t prometheus__metric_metadata__pack_to_buffer
                     (const Prometheus__MetricMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &prometheus__metric_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Prometheus__MetricMetadata *
       prometheus__metric_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Prometheus__MetricMetadata *)
     protobuf_c_message_unpack (&prometheus__metric_metadata__descriptor,
                                allocator, len, data);
}
void   prometheus__metric_metadata__free_unpacked
                     (Prometheus__MetricMetadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &prometheus__metric_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor prometheus__label__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Prometheus__Label, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Prometheus__Label, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned prometheus__label__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange prometheus__label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor prometheus__label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "prometheus.Label",
  "Label",
  "Prometheus__Label",
  "prometheus",
  sizeof(Prometheus__Label),
  2,
  prometheus__label__field_descriptors,
  prometheus__label__field_indices_by_name,
  1,  prometheus__label__number_ranges,
  (ProtobufCMessageInit) prometheus__label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor prometheus__sample__field_descriptors[2] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Prometheus__Sample, has_value),
    offsetof(Prometheus__Sample, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Prometheus__Sample, has_timestamp),
    offsetof(Prometheus__Sample, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned prometheus__sample__field_indices_by_name[] = {
  1,   /* field[1] = timestamp */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange prometheus__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor prometheus__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "prometheus.Sample",
  "Sample",
  "Prometheus__Sample",
  "prometheus",
  sizeof(Prometheus__Sample),
  2,
  prometheus__sample__field_descriptors,
  prometheus__sample__field_indices_by_name,
  1,  prometheus__sample__number_ranges,
  (ProtobufCMessageInit) prometheus__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor prometheus__time_series__field_descriptors[2] =
{
  {
    "labels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Prometheus__TimeSeries, n_labels),
    offsetof(Prometheus__TimeSeries, labels),
    &prometheus__label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "samples",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Prometheus__TimeSeries, n_samples),
    offsetof(Prometheus__TimeSeries, samples),
    &prometheus__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned prometheus__time_series__field_indices_by_name[] = {
  0,   /* field[0] = labels */
  1,   /* field[1] = samples */
};
static const ProtobufCIntRange prometheus__time_series__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor prometheus__time_series__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "prometheus.TimeSeries",
  "TimeSeries",
  "Prometheus__TimeSeries",
  "prometheus",
  sizeof(Prometheus__TimeSeries),
  2,
  prometheus__time_series__field_descriptors,
  prometheus__time_series__field_indices_by_name,
  1,  prometheus__time_series__number_ranges,
  (ProtobufCMessageInit) prometheus__time_series__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define prometheus__metric_metadata__field_descriptors NULL
#define prometheus__metric_metadata__field_indices_by_name NULL
#define prometheus__metric_metadata__number_ranges NULL
const ProtobufCMessageDescriptor prometheus__metric_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "prometheus.MetricMetadata",
  "MetricMetadata",
  "Prometheus__MetricMetadata",
  "prometheus",
  sizeof(Prometheus__MetricMetadata),
  0,
  prometheus__metric_metadata__field_descriptors,
  prometheus__metric_metadata__field_indices_by_name,
  0,  prometheus__metric_metadata__number_ranges,
  (ProtobufCMessageInit) prometheus__metric_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
